{{- if .Values.hpa.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
    app: "{{ .Release.Name }}-{{ .Values.environment }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release:  {{ .Release.Name }}
    environment: {{ .Values.environment }}
spec:
  minReplicas: {{ .Values.hpa.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hpa.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.autoscaling.targetCPU }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
{{- end }}