{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: "{{ .Release.Name }}-{{ .Values.environment }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release:  {{ .Release.Name }}
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.ports.name }}
    port: {{ .Values.service.ports.port }}
    protocol: {{ .Values.service.ports.protocol }}
    targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: "{{ .Release.Name }}-{{ .Values.environment }}"
{{- end }}